git_repo = "git@github.com:yourusername/dotfiles.git"
cache_dir = "~/.cache/harddots"

[[applications]]
name = "starship"
target_path = "~/.config/starship.toml"
source_git_path = "starship/starship.toml"
version = ">= 1.10.0"
[applications.packages]
macos = "starship"
debian = "starship"
alpine = "starship"

[[applications]]
name = "tmux"
target_path = "~/.tmux.conf"
source_git_path = "tmux/tmux.conf"
[applications.packages]
macos = "tmux"
debian = "tmux"
alpine = "tmux"

[[applications]]
name = "neovim"
target_path = "~/.config/nvim/init.lua"
source_git_path = "nvim/init.lua"
[applications.packages]
macos = "neovim"
debian = "neovim"
[applications.custom_install]
alpine = "apk add neovim --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community"

