git_repo = "git@github.com:l1x/dotfiles.git"
cache_dir = "~/.cache/harddots"

[[applications]]
name = "ssh"
target_path = "~/.ssh/config"
source_git_path = "ssh-client/config"

[applications.packages]
macos = "openssh"
debian = "openssh-client"
alpine = "openssh-client"

[[applications]]
name = "starship"
target_path = "~/.config/starship.toml"
source_git_path = "starship/starship.toml"

[applications.packages]
macos = "starship"
debian = "starship"
alpine = "starship"

[[applications]]
name = "tmux"
target_path = "~/.tmux.conf"
source_git_path = "tmux/tmux.conf"

[applications.packages]
macos = "tmux"
debian = "tmux"
alpine = "tmux"

[[applications]]
name = "fish"
target_path = "~/.config/fish/config.fish"
source_git_path = "fish/config"

[applications.packages]
macos = "fish"
debian = "fish"
alpine = "fish"
